//
// Created by mathieu on 15/05/16.
//

#ifndef CRAZYMARBLE3DCLION_LVLEDITORMAPBUTTON_H
#define CRAZYMARBLE3DCLION_LVLEDITORMAPBUTTON_H


class LvlEditorMapButton {

};


#endif //CRAZYMARBLE3DCLION_LVLEDITORMAPBUTTON_H
