//
// Created by mathieu on 15/05/16.
//

#ifndef CRAZYMARBLE3DCLION_FILESYSTEMUTILS_H
#define CRAZYMARBLE3DCLION_FILESYSTEMUTILS_H


class FileSystemUtils {

};


#endif //CRAZYMARBLE3DCLION_FILESYSTEMUTILS_H
